### ISSUE TITLE
Backslash problem upon client deployment on windows environment

### ISSUE THREAD

**Issue by jamesfigues** [serverless/serverless-client-s3#16]
Running "sls client deploy" in windows environment will not properly structure the files of the project. It will not automatically create new folders which I think caused by the "\" on the file locations. Please see image below for reference:

![windows](https://cloud.githubusercontent.com/assets/3445607/14523991/d7d990e8-0268-11e6-9807-482ce3c90c19.png)

The image below is from a deployment in mac environment which worked out just fine.

![mac](https://cloud.githubusercontent.com/assets/3445607/14523992/d7dbbcd8-0268-11e6-901e-82e20c5546b6.png)

**Comment by BerndWessels** [comment]
Yes, I experience the same.

**Comment by BerndWessels** [comment]
@jamesfigues was right and I made [this PR](https://github.com/serverless/serverless-client-s3/pull/19) with a simple fix.

**Comment by eahefnawy** [comment]
Sorry for the late reply on this one guys. I Just merged @BerndWessels PR. Haven't released yet though. Could you guys confirm that its working for windows using the master branch?

**Comment by BerndWessels** [comment]
@eahefnawy Thanks for pulling. I tried it on Win 10 and 8. The fix is so minor that I am pretty sure it will work on all Windows an not break anything else.
