### ISSUE TITLE
Publicly vs Publically

### ISSUE THREAD

**Issue by alexandresaiz** [serverless/serverless-client-s3#4]
I was going to do a PR to replace publically for publicly because I didn't find it either here:
http://www.wordreference.com/es/translation.asp?tranword=publically

nor here:

http://www.wordreference.com/es/translation.asp?tranword=publically

so I eventually came up with this: 
http://english.stackexchange.com/questions/45136/difference-between-publicly-and-publically?newreg=4d54d0dc2f464e64af6566ab628052f7

So I leave up to you. I, personally find strange "publically".
Sorry @eahefnawy for being too weary!

**Comment by eahefnawy** [comment]
Thanks @alexandresaiz ... I changed to `publicly` ... I looks easier to digest :blush:

**Comment by alexandresaiz** [comment]
👍 closing
